CREATE DATABASE IF NOT EXISTS wifirental;
USE wifirental;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(32) UNIQUE, name VARCHAR(128), password_hash VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS partners (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(32), share_percent INT DEFAULT 70, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hotspots (id INT AUTO_INCREMENT PRIMARY KEY, partner_id INT, name VARCHAR(128), router_host VARCHAR(128), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id INT AUTO_INCREMENT PRIMARY KEY, external_id VARCHAR(255), provider VARCHAR(64), provider_reference VARCHAR(255), amount_cents INT, status VARCHAR(32), phone VARCHAR(32), plan_id INT, hotspot_id INT, partner_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hotspot_earnings (id INT AUTO_INCREMENT PRIMARY KEY, payment_id INT, hotspot_id INT, partner_id INT, amount_cents INT, partner_share_cents INT, platform_share_cents INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
